FROM python:3.12-slim

WORKDIR /opt/ai-news-agent

# Установка зависимостей
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копирование исходного кода
COPY . .

# Запуск агента (scheduler)
CMD ["python", "scheduler.py"]
